### ISSUE TITLE
加载示例应用help.ts报错

### ISSUE THREAD

**Issue by gelidrain** [ningmengchongshui/alemon#7]
作者大大你好，我在使用 `pnpm create alemonjs@latest -y` 命令创建项目后，只按照文档修改了 `a.login.config.ts` 登录配置文件，没有修改其他代码，但是加载项目自带的示例应用时出错了：
[APP] [local dev] apps/img/help.ts(1,27): error TS2305: Module '"alemonjs"' has no exported member 'AInstruct'.

我的 Node.js 版本是 v18.18.2，TypeScript 版本是 5.3.2. 各个依赖的版本如下：
- alemonjs@1.0.0
- ioredis 5.3.2
- mysql2 3.7.1
- sequelize 6.35.2
- afloat 1.1.13
- alemonjs 1.2.0-rc.15
- pm2 5.3.1
- prettier 3.2.4

**Comment by ningmengchongshui** [comment]
应该是脚手架并没有清理干掉。把报错的代码清了就好了，不影响正常使用。

**Comment by ningmengchongshui** [comment]
那个只是示例功能，核心的东西都封装起来了，并不会造成框架出现BUG

**Comment by gelidrain** [comment]
好滴明白了，谢谢解答

**Comment by ningmengchongshui** [comment]
已经推送新版安装示例说明，推荐使用 pnpm create alemonjs@latest -y 安装最新版，npm有时候会存在网络延迟或缓存问题
